name: remote_flutter_translate
description: Remote Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 1.0.2
repository: https://github.com/Nolle10/remote_flutter_translate

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0
